apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: shagun
type: Opaque
data:
  secret: WlRBNFlUa3dabU5oWXpSbVkyTmtNbVUxWTJZelpEYzJaRFZoWVdJMU1UVmpNakEwT0dVd09UazFaakkzWXpWbVptUmhaRFUyWmpGbE5tTTVaakZqTTJaak1HTTROV0ptTnpVMU1tSmtNamMzTjJVME9XSmlZakkxT1RFNE1UUXhZamRrWlE9PQ==
